'use client';
import { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

const translations = {
  en: {
    // Sidebar
    sidebar: {
      logo: "FinanceCalc",
      dashboard: "Dashboard",
      accountHolders: "Account Holders",
      bills: "Bills",
      payments: "Payments",
      reports: "Reports",
      users: "Users",
      settings: "Settings",
      signOut: "Sign Out",
    },
    // Common / Buttons / General
    common: {
      cancel: "Cancel",
      save: "Save Changes",
      saving: "Saving...",
      create: "Create",
      creating: "Creating...",
      delete: "Delete",
      actions: "Actions",
      status: "Status",
      type: "Type",
      amount: "Amount",
      date: "Date",
      description: "Description",
      note: "Note",
      reference: "Reference",
      loading: "Loading...",
      noData: "No data available.",
      back: "Back",
      edit: "Edit",
      reset: "Reset",
      search: "Search...",
      allStatus: "All Status",
      allTime: "All Time",
      monthly: "Monthly",
      ok: "OK",
      langEnglish: "English",
      langBangla: "Bangla",
    },
    // Dashboard
    dashboard: {
      title: "Dashboard",
      subtitle: "Overview of your financial activity",
      totalCollected: "Total Collected",
      totalPaidOut: "Total Paid Out",
      outstandingReceivables: "Outstanding Receivables",
      outstandingPayables: "Outstanding Payables",
      moneyReceived: "Money Received",
      moneySent: "Money Sent",
      toBeCollected: "To be collected",
      toBePaid: "To be paid",
      recentBills: "Recent Bills",
      recentPayments: "Recent Payments",
      viewAll: "View All",
      billNo: "Bill #",
      account: "Account",
      noBills: "No bills yet",
      noPayments: "No payments yet",
    },
    // Account Holders Page
    accountHolders: {
      title: "Account Holders",
      subtitle: "Manage your vendors, clients, and contacts",
      newHolder: "+ New Account Holder",
      name: "Name",
      bank: "Bank",
      totalBilled: "Total Billed",
      collected: "Collected",
      paidOut: "Paid Out",
      outstanding: "Outstanding",
      noHolders: "No Account Holders Yet",
      noHoldersSub: "Create your first account holder to start tracking bills and payments",
      createHolder: "Create Account Holder",
      newHolderTitle: "New Account Holder",
      bankName: "Bank Name",
      accountName: "Account Name",
      accountNumber: "Account Number",
      phone: "Phone",
      email: "Email",
      address: "Address",
      notes: "Notes",
      vendor: "Vendor",
      client: "Client",
      both: "Both",
      deleteConfirm: "Delete this account holder and all associated bills/payments?",
      failedDelete: "Failed to delete account holder",
    },
    // Account Holder Detail Page
    accountHolderDetail: {
      backLink: "← Back to Account Holders",
      addBill: "📄 Add Bill",
      addPayment: "💰 Add Payment",
      report: "📈 Report",
      totalBilledR: "Total Billed (R)",
      totalBilledP: "Total Billed (P)",
      totalCollected: "Total Collected",
      totalPaidOut: "Total Paid Out",
      outstanding: "Outstanding",
      bank: "Bank",
      accountName: "Account Name",
      accountNumber: "Account #",
      phone: "Phone",
      email: "Email",
      address: "Address",
      notes: "Notes",
      bills: "Bills",
      payments: "Payments",
      noBillsYet: "No bills yet — click \"Add Bill\" to create one",
      noPaymentsYet: "No payments yet",
      addBillModalTitle: "Add Bill for",
      billType: "Bill Type",
      billTypeR: "Collecting Money (Receivable)",
      billTypeP: "Giving Money (Payable)",
      amountLabel: "Amount *",
      dueDate: "Due Date",
      descriptionPlaceholder: "What is this bill for?",
      addPaymentModalTitle: "Record Payment for",
      selectBill: "Select Bill *",
      selectBillPlaceholder: "Choose a bill...",
      paymentDate: "Date *",
      paymentMethod: "Method",
      cash: "Cash",
      bankTransfer: "Bank Transfer",
      cheque: "Cheque",
      mobileBanking: "Mobile Banking",
      other: "Other",
      referencePlaceholder: "Cheque/Transfer ref",
      generateReportTitle: "Generate Report for",
      generateReportSub: "Choose a specific month or generate for all time",
      selectMonth: "Select Month",
      allTimeReportBtn: "📄 All Time Report",
      monthlyReportBtn: "📈 Monthly Report",
      deleteBillConfirm: "Delete this bill? (Only allowed if no payments exist)",
      deletePaymentConfirm: "Delete this payment? The bill status will be recalculated.",
      statusUnpaid: "unpaid",
      statusPartial: "partial",
      statusPaid: "paid",
      addBillFor: "Add Bill for",
      billTypeDescR: "Collecting Money (Receivable)",
      billTypeDescP: "Giving Money (Payable)",
      billDescPlaceholder: "What is this bill for?",
      recordPaymentFor: "Record Payment for",
      chooseBill: "Choose a bill...",
      payRefPlaceholder: "Cheque/Transfer ref",
      recordPayment: "Record Payment",
      generateReportFor: "Generate Report for",
      chooseTimeRange: "Choose a specific month or generate for all time",
      allTimeReport: "All Time Report",
      monthlyReport: "Monthly Report",
      selectReportLang: "Select Report Language",
      chooseReportLangDesc: "Choose which language the report should be generated in:",
      payTypeR: "Received",
      payTypeP: "Paid",
    },
    // Bills Page
    bills: {
      title: "Bills",
      subtitle: "Track all your invoices and bills",
      newBill: "+ New Bill",
      created: "Created",
      noBills: "No Bills Yet",
      noBillsSub: "Create your first bill to start tracking",
      createBillBtn: "+ Create Bill",
      billNumber: "Bill #",
      accountHolder: "Account Holder",
      allStatus: "All Status",
    },
    // Bill Detail Page
    billDetail: {
      backLink: "← Back to Bills",
      collectMoney: "Collect Money",
      recordPayment: "Record Payment",
      deleteBillBtn: "🗑️ Delete",
      billAmount: "Bill Amount",
      paid: "Paid",
      remaining: "Remaining",
      paymentProgress: "Payment Progress",
      deleteConfirm: "Delete this bill and all its payments?",
      progress: "Payment Progress",
      noDueDate: "No due date",
      collectPayment: "Collect Payment",
    },
    // New Bill Page
    newBill: {
      backLink: "← Back to Bills",
      title: "Create New Bill",
      accountHolder: "Account Holder",
      selectHolder: "Select account holder",
      billTypeLabel: "Bill Type *",
      amountLabel: "Amount *",
      dueDateLabel: "Due Date",
      createBtn: "Create Bill",
    },
    // Payments Page
    payments: {
      title: "Payments",
      subtitle: "All payment records",
      noPayments: "No Payments Yet",
      noPaymentsSub: "Payments appear here when you record them against bills",
      deleteConfirm: "Delete this payment?",
      total: "Total",
      method: "Method",
      reference: "Reference",
      cash: "Cash",
      bankTransfer: "Bank Transfer",
      cheque: "Cheque",
      mobile: "Mobile Banking",
      other: "Other",
    },
    // Reports Page
    reports: {
      title: "Reports",
      subtitle: "Generate and export PDF reports",
      dateFilterTitle: "Global Date Filter (Optional)",
      dateFilterSub: "Apply a date range to your reports. Leave blank for all time.",
      startDate: "Start Date",
      endDate: "End Date",
      outstandingCardTitle: "Outstanding Balances",
      outstandingCardDesc: "A list of all unpaid and partially paid bills across all account holders.",
      paymentSummaryCardTitle: "Payment Summary",
      paymentSummaryCardDesc: "Total payments received/sent, grouped by account holder.",
      fullTransactionsCardTitle: "Full Transactions",
      fullTransactionsCardDesc: "A combined chronological list of all bills and payments.",
      accountStatementCardTitle: "Account Statement",
      accountStatementCardDesc: "Complete history of bills and payments for a specific account holder.",
      selectHolderPlaceholder: "Select Account Holder...",
      generatePdfBtn: "Generate PDF",
      langModalTitle: "🌐 Select Report Language",
      langModalSub: "Choose which language the report should be generated in:",
      langEnBtn: "🇬🇧 English",
      langBnBtn: "🇧🇩 বাংলা",
      selectHolderAlert: "Please select an account holder",
      globalDateFilter: "Global Date Filter (Optional)",
      dateFilterDesc: "Apply a date range to your reports. Leave blank for all time.",
      outstandingBalances: "Outstanding Balances",
      outstandingBalancesDesc: "A list of all unpaid and partially paid bills across all account holders.",
      paymentSummary: "Payment Summary",
      paymentSummaryDesc: "Total payments received/sent, grouped by account holder.",
      fullTransactions: "Full Transactions",
      fullTransactionsDesc: "A combined chronological list of all bills and payments.",
      accountStatement: "Account Statement",
      accountStatementDesc: "Complete history of bills and payments for a specific account holder.",
      generatePdf: "Generate PDF",
    },
    // Users Page
    users: {
      title: "User Management",
      subtitle: "View and manage all registered users",
      totalUsers: "Total Users",
      admins: "Admins",
      regularUsers: "Regular Users",
      searchPlaceholder: "Search by name or email...",
      noUsersTitle: "No Users Found",
      noUsersDesc: "No users match your search criteria.",
      colUser: "User",
      colEmail: "Email",
      colRole: "Role",
      colStatus: "Status",
      colJoined: "Joined",
      colActions: "Actions",
      btnReset: "🔑 Reset",
      btnActivate: "🔥 Activate",
      btnFreeze: "❄️ Freeze",
      roleAdmin: "🛡️ Admin",
      roleUser: "👤 User",
      statusActive: "✅ Active",
      statusFrozen: "❄️ Frozen",
      accessDeniedTitle: "Access Denied",
      accessDeniedDesc: "You do not have permission to view this page. Contact your administrator.",
      modalResetTitle: "Reset Password",
      modalResetSub: "Set a new password for",
      newPasswordLabel: "New Password",
      confirmPasswordLabel: "Confirm New Password",
      resettingBtn: "Resetting...",
      resetPasswordBtn: "Reset Password",
      resetSuccess: "Password reset successfully",
      failedToggle: "Failed to change user status",
      accessDenied: "Access Denied",
      noUsersFound: "No Users Found",
      noUsersFoundDesc: "No users match your search criteria.",
      user: "User",
      joined: "Joined",
      actions: "Actions",
      frozen: "Frozen",
      active: "Active",
      reset: "Reset",
      activate: "Activate",
      freeze: "Freeze",
      resetPasswordFor: "Set a new password for",
    },
    // Settings Page
    settings: {
      title: "Settings",
      subtitle: "Manage your account preferences",
      profileTitle: "👤 Profile Information",
      roleLabel: "Role",
      changePasswordTitle: "🔒 Change Password",
      currentPasswordLabel: "Current Password",
      newPasswordLabel: "New Password",
      confirmPasswordLabel: "Confirm New Password",
      currentPasswordPlaceholder: "Enter your current password",
      newPasswordPlaceholder: "Min 6 characters",
      confirmPasswordPlaceholder: "••••••••",
      updatePasswordBtn: "Update Password",
      updatingBtn: "Updating...",
      passwordsDoNotMatch: "New passwords do not match",
      passwordTooShort: "New password must be at least 6 characters",
      passwordChangedSuccess: "Password changed successfully",
      profileInfo: "Profile Information",
      role: "Role",
      roleAdmin: "Admin",
      roleUser: "User",
      changePassword: "Change Password",
      currentPassword: "Current Password",
      currentPassPlaceholder: "Enter your current password",
      newPassPlaceholder: "Min 6 characters",
      confirmPassword: "Confirm New Password",
    },
  },
  bn: {
    // Sidebar
    sidebar: {
      logo: "ফাইন্যান্সক্যালক",
      dashboard: "ড্যাশবোর্ড",
      accountHolders: "হিসাবধারী",
      bills: "বিল সমূহ",
      payments: "পেমেন্ট সমূহ",
      reports: "রিপোর্ট সমূহ",
      users: "ব্যবহারকারী",
      settings: "সেটিংস",
      signOut: "লগ আউট",
    },
    // Common / Buttons / General
    common: {
      cancel: "বাতিল",
      save: "পরিবর্তন সংরক্ষণ",
      saving: "সংরক্ষণ হচ্ছে...",
      create: "তৈরি করুন",
      creating: "তৈরি হচ্ছে...",
      delete: "মুছে ফেলুন",
      actions: "কার্যক্রম",
      status: "অবস্থা",
      type: "ধরন",
      amount: "পরিমাণ",
      date: "তারিখ",
      description: "বিবরণ",
      note: "নোট",
      reference: "রেফারেন্স",
      loading: "লোড হচ্ছে...",
      noData: "কোনো তথ্য উপলব্ধ নেই।",
      back: "পেছনে",
      edit: "সম্পাদনা",
      reset: "রিসেট",
      search: "খুঁজুন...",
      allStatus: "সব অবস্থা",
      allTime: "সর্বকালীন",
      monthly: "মাসিক",
      ok: "ঠিক আছে",
      langEnglish: "English",
      langBangla: "বাংলা",
    },
    // Dashboard
    dashboard: {
      title: "ড্যাশবোর্ড",
      subtitle: "আপনার আর্থিক কার্যক্রমের সংক্ষিপ্ত বিবরণ",
      totalCollected: "মোট সংগৃহীত",
      totalPaidOut: "মোট পরিশোধিত",
      outstandingReceivables: "বকেয়া পাওনা (রিসিভেবল)",
      outstandingPayables: "বকেয়া দেনা (পেয়াবল)",
      moneyReceived: "সংগৃহীত অর্থ",
      moneySent: "পরিশোধিত অর্থ",
      toBeCollected: "সংগ্রহ করতে হবে",
      toBePaid: "পরিশোধ করতে হবে",
      recentBills: "সাম্প্রতিক বিল সমূহ",
      recentPayments: "সাম্প্রতিক পেমেন্ট সমূহ",
      viewAll: "সব দেখুন",
      billNo: "বিল নং",
      account: "হিসাব",
      noBills: "এখনো কোনো বিল নেই",
      noPayments: "এখনো কোনো পেমেন্ট নেই",
    },
    // Account Holders Page
    accountHolders: {
      title: "হিসাবধারীগণ",
      subtitle: "আপনার ভেন্ডর, ক্লায়েন্ট এবং পরিচিতিগুলো পরিচালনা করুন",
      newHolder: "+ নতুন হিসাবধারী",
      name: "নাম",
      bank: "ব্যাংক",
      totalBilled: "মোট বিল",
      collected: "সংগৃহীত",
      paidOut: "পরিশোধিত",
      outstanding: "বকেয়া",
      noHolders: "এখনো কোনো হিসাবধারী নেই",
      noHoldersSub: "বিল এবং পেমেন্ট ট্র্যাকিং শুরু করতে প্রথম হিসাবধারী তৈরি করুন",
      createHolder: "হিসাবধারী তৈরি করুন",
      newHolderTitle: "নতুন হিসাবধারী",
      bankName: "ব্যাংকের নাম",
      accountName: "হিসাবের নাম",
      accountNumber: "হিসাব নম্বর",
      phone: "ফোন নম্বর",
      email: "ইমেইল",
      address: "ঠিকানা",
      notes: "নোট",
      vendor: "ভেন্ডর",
      client: "ক্লায়েন্ট",
      both: "উভয়",
      deleteConfirm: "আপনি কি নিশ্চিতভাবে এই হিসাবধারী এবং সংশ্লিষ্ট সকল বিল/পেমেন্ট মুছে ফেলতে চান?",
      failedDelete: "হিসাবধারী মুছতে ব্যর্থ হয়েছে",
    },
    // Account Holder Detail Page
    accountHolderDetail: {
      backLink: "← হিসাবধারী তালিকায় ফিরে যান",
      addBill: "📄 বিল যুক্ত করুন",
      addPayment: "💰 পেমেন্ট যুক্ত করুন",
      report: "📈 রিপোর্ট",
      totalBilledR: "মোট বিল (রিসিভেবল)",
      totalBilledP: "মোট বিল (পেয়াবল)",
      totalCollected: "মোট সংগৃহীত",
      totalPaidOut: "মোট পরিশোধিত",
      outstanding: "বকেয়া",
      bank: "ব্যাংক",
      accountName: "হিসাবের নাম",
      accountNumber: "হিসাব #",
      phone: "ফোন",
      email: "ইমেইল",
      address: "ঠিকানা",
      notes: "নোট",
      bills: "বিল সমূহ",
      payments: "পেমেন্ট সমূহ",
      noBillsYet: "এখনো কোনো বিল নেই — বিল তৈরি করতে \"বিল যুক্ত করুন\" ক্লিক করুন",
      noPaymentsYet: "এখনো কোনো পেমেন্ট নেই",
      addBillModalTitle: "বিল তৈরি করুন - হিসাবধারী:",
      billType: "বিলের ধরন",
      billTypeR: "টাকা সংগ্রহ (রিসিভেবল)",
      billTypeP: "টাকা প্রদান (পেয়াবল)",
      amountLabel: "পরিমাণ *",
      dueDate: "পরিশোধের শেষ তারিখ",
      descriptionPlaceholder: "এই বিলটি কি জন্য?",
      addPaymentModalTitle: "পেমেন্ট রেকর্ড করুন - হিসাবধারী:",
      selectBill: "বিল নির্বাচন করুন *",
      selectBillPlaceholder: "একটি বিল চয়ন করুন...",
      paymentDate: "তারিখ *",
      paymentMethod: "পদ্ধতি",
      cash: "নগদ",
      bankTransfer: "ব্যাংক ট্রান্সফার",
      cheque: "চেক",
      mobileBanking: "মোবাইল ব্যাংকিং",
      other: "অন্যান্য",
      referencePlaceholder: "চেক/ট্রান্সফার রেফারেন্স",
      generateReportTitle: "রিপোর্ট তৈরি করুন - হিসাবধারী:",
      generateReportSub: "একটি নির্দিষ্ট মাস নির্বাচন করুন অথবা সর্বকালীন রিপোর্ট তৈরি করুন",
      selectMonth: "মাস নির্বাচন করুন",
      allTimeReportBtn: "📄 সর্বকালীন রিপোর্ট",
      monthlyReportBtn: "📈 মাসিক রিপোর্ট",
      deleteBillConfirm: "আপনি কি এই বিলটি মুছে ফেলতে চান? (কোনো পেমেন্ট না থাকলেই কেবল সম্ভব)",
      deletePaymentConfirm: "আপনি কি এই পেমেন্টটি মুছে ফেলতে চান? বিলের অবস্থা পুনরায় হিসাব করা হবে।",
      statusUnpaid: "অপরিশোধিত",
      statusPartial: "আংশিক",
      statusPaid: "পরিশোধিত",
      addBillFor: "বিল যুক্ত করুন - হিসাবধারী:",
      billTypeDescR: "টাকা সংগ্রহ (রিসিভেবল)",
      billTypeDescP: "টাকা প্রদান (পেয়াবল)",
      billDescPlaceholder: "এই বিলটি কি জন্য?",
      recordPaymentFor: "পেমেন্ট রেকর্ড করুন - হিসাবধারী:",
      chooseBill: "একটি বিল চয়ন করুন...",
      payRefPlaceholder: "চেক/ট্রান্সফার রেফারেন্স",
      recordPayment: "পেমেন্ট রেকর্ড করুন",
      generateReportFor: "রিপোর্ট তৈরি করুন - হিসাবধারী:",
      chooseTimeRange: "একটি নির্দিষ্ট মাস নির্বাচন করুন অথবা সর্বকালীন রিপোর্ট তৈরি করুন",
      allTimeReport: "সর্বকালীন রিপোর্ট",
      monthlyReport: "মাসিক রিপোর্ট",
      selectReportLang: "রিপোর্টের ভাষা নির্বাচন করুন",
      chooseReportLangDesc: "রিপোর্টটি কোন ভাষায় তৈরি করতে চান তা চয়ন করুন:",
      payTypeR: "সংগৃহীত",
      payTypeP: "পরিশোধিত",
    },
    // Bills Page
    bills: {
      title: "বিল সমূহ",
      subtitle: "আপনার সকল ইনভয়েস এবং বিল ট্র্যাক করুন",
      newBill: "+ নতুন বিল",
      created: "তৈরি করা হয়েছে",
      noBills: "এখনো কোনো বিল নেই",
      noBillsSub: "ট্র্যাকিং শুরু করতে আপনার প্রথম বিল তৈরি করুন",
      createBillBtn: "+ বিল তৈরি করুন",
      billNumber: "বিল #",
      accountHolder: "হিসাবধারী",
      allStatus: "সব অবস্থা",
    },
    // Bill Detail Page
    billDetail: {
      backLink: "← বিল তালিকায় ফিরে যান",
      collectMoney: "টাকা সংগ্রহ করুন",
      recordPayment: "পেমেন্ট রেকর্ড করুন",
      deleteBillBtn: "🗑️ মুছুন",
      billAmount: "বিলের পরিমাণ",
      paid: "পরিশোধিত",
      remaining: "অবশিষ্ট",
      paymentProgress: "পরিশোধের অগ্রগতি",
      deleteConfirm: "আপনি কি এই বিল এবং এর সমস্ত পেমেন্ট মুছে ফেলতে চান?",
      progress: "পরিশোধের অগ্রগতি",
      noDueDate: "কোনো পরিশোধের শেষ তারিখ নেই",
      collectPayment: "টাকা সংগ্রহ করুন",
    },
    // New Bill Page
    newBill: {
      backLink: "← বিল তালিকায় ফিরে যান",
      title: "নতুন বিল তৈরি করুন",
      accountHolder: "হিসাবধারী",
      selectHolder: "হিসাবধারী নির্বাচন করুন",
      billTypeLabel: "বিলের ধরন *",
      amountLabel: "পরিমাণ *",
      dueDateLabel: "পরিশোধের শেষ তারিখ",
      createBtn: "বিল তৈরি করুন",
    },
    // Payments Page
    payments: {
      title: "পেমেন্ট সমূহ",
      subtitle: "সমস্ত পেমেন্ট রেকর্ড",
      noPayments: "এখনো কোনো পেমেন্ট নেই",
      noPaymentsSub: "বিলের বিপরীতে পেমেন্ট রেকর্ড করলে তা এখানে প্রদর্শিত হবে",
      deleteConfirm: "আপনি কি এই পেমেন্টটি মুছে ফেলতে চান?",
      total: "মোট",
      method: "পদ্ধতি",
      reference: "রেফারেন্স",
      cash: "নগদ",
      bankTransfer: "ব্যাংক ট্রান্সফার",
      cheque: "চেক",
      mobile: "মোবাইল ব্যাংকিং",
      other: "অন্যান্য",
    },
    // Reports Page
    reports: {
      title: "রিপোর্ট সমূহ",
      subtitle: "পিডিএফ রিপোর্ট তৈরি এবং রপ্তানি করুন",
      dateFilterTitle: "গ্লোবাল ডেট ফিল্টার (ঐচ্ছিক)",
      dateFilterSub: "রিপোর্টে একটি তারিখের ব্যাপ্তি প্রয়োগ করুন। সব সময়ের জন্য ফাঁকা রাখুন।",
      startDate: "শুরুর তারিখ",
      endDate: "শেষের তারিখ",
      outstandingCardTitle: "বকেয়া ব্যালেন্স",
      outstandingCardDesc: "সকল হিসাবধারীর পরিশোধিত নয় বা আংশিক পরিশোধিত বিলের তালিকা।",
      paymentSummaryCardTitle: "পেমেন্ট সারাংশ",
      paymentSummaryCardDesc: "হিসাবধারী ভিত্তিক প্রাপ্ত/প্রদত্ত মোট পেমেন্টের সারাংশ।",
      fullTransactionsCardTitle: "সম্পূর্ণ লেনদেন",
      fullTransactionsCardDesc: "ক্রমানুসারে সাজানো সকল বিল এবং পেমেন্টের যৌথ তালিকা।",
      accountStatementCardTitle: "হিসাব বিবরণী",
      accountStatementCardDesc: "একটি নির্দিষ্ট হিসাবধারীর বিল এবং পেমেন্টের সম্পূর্ণ ইতিহাস।",
      selectHolderPlaceholder: "হিসাবধারী নির্বাচন করুন...",
      generatePdfBtn: "পিডিএফ তৈরি করুন",
      langModalTitle: "🌐 রিপোর্টের ভাষা নির্বাচন করুন",
      langModalSub: "রিপোর্টটি কোন ভাষায় তৈরি করতে চান তা চয়ন করুন:",
      langEnBtn: "🇬🇧 English",
      langBnBtn: "🇧🇩 বাংলা",
      selectHolderAlert: "অনুগ্রহ করে একজন হিসাবধারী নির্বাচন করুন",
      globalDateFilter: "গ্লোবাল ডেট ফিল্টার (ঐচ্ছিক)",
      dateFilterDesc: "রিপোর্টে একটি তারিখের ব্যাপ্তি প্রয়োগ করুন। সব সময়ের জন্য ফাঁকা রাখুন।",
      outstandingBalances: "বকেয়া ব্যালেন্স",
      outstandingBalancesDesc: "সকল হিসাবধারীর পরিশোধিত নয় বা আংশিক পরিশোধিত বিলের তালিকা।",
      paymentSummary: "পেমেন্ট সারাংশ",
      paymentSummaryDesc: "হিসাবধারী ভিত্তিক প্রাপ্ত/প্রদত্ত মোট পেমেন্টের সারাংশ।",
      fullTransactions: "সম্পূর্ণ লেনদেন",
      fullTransactionsDesc: "ক্রমানুসারে সাজানো সকল বিল এবং পেমেন্টের যৌথ তালিকা।",
      accountStatement: "হিসাব বিবরণী",
      accountStatementDesc: "একটি নির্দিষ্ট হিসাবধারীর বিল এবং পেমেন্টের সম্পূর্ণ ইতিহাস।",
      generatePdf: "পিডিএফ তৈরি করুন",
    },
    // Users Page
    users: {
      title: "ব্যবহারকারী পরিচালনা",
      subtitle: "নিবন্ধিত সকল ব্যবহারকারী দেখুন ও পরিচালনা করুন",
      totalUsers: "মোট ব্যবহারকারী",
      admins: "অ্যাডমিনগণ",
      regularUsers: "সাধারণ ব্যবহারকারী",
      searchPlaceholder: "নাম বা ইমেইল দিয়ে খুঁজুন...",
      noUsersTitle: "কোনো ব্যবহারকারী পাওয়া যায়নি",
      noUsersDesc: "আপনার অনুসন্ধানের সাথে কোনো ব্যবহারকারী মিলেনি।",
      colUser: "ব্যবহারকারী",
      colEmail: "ইমেইল",
      colRole: "ভূমিকা",
      colStatus: "অবস্থা",
      colJoined: "যোগদান",
      colActions: "কার্যক্রম",
      btnReset: "🔑 রিসেট",
      btnActivate: "🔥 সক্রিয় করুন",
      btnFreeze: "❄️ ফ্রিজ করুন",
      roleAdmin: "🛡️ অ্যাডমিন",
      roleUser: "👤 ব্যবহারকারী",
      statusActive: "✅ সক্রিয়",
      statusFrozen: "❄️ ফ্রিজড",
      accessDeniedTitle: "প্রবেশাধিকার নিষিদ্ধ",
      accessDeniedDesc: "এই পৃষ্ঠাটি দেখার অনুমতি আপনার নেই। আপনার অ্যাডমিনের সাথে যোগাযোগ করুন।",
      modalResetTitle: "পাসওয়ার্ড রিসেট",
      modalResetSub: "এর জন্য একটি নতুন পাসওয়ার্ড সেট করুন",
      newPasswordLabel: "নতুন পাসওয়ার্ড",
      confirmPasswordLabel: "নতুন পাসওয়ার্ড নিশ্চিত করুন",
      resettingBtn: "রিসেট হচ্ছে...",
      resetPasswordBtn: "পাসওয়ার্ড রিসেট করুন",
      resetSuccess: "পাসওয়ার্ড সফলভাবে রিসেট করা হয়েছে",
      failedToggle: "ব্যবহারকারীর অবস্থা পরিবর্তন করতে ব্যর্থ হয়েছে",
      accessDenied: "প্রবেশাধিকার নিষিদ্ধ",
      noUsersFound: "কোনো ব্যবহারকারী পাওয়া যায়নি",
      noUsersFoundDesc: "আপনার অনুসন্ধানের সাথে কোনো ব্যবহারকারী মিলেনি।",
      user: "ব্যবহারকারী",
      joined: "যোগদান",
      actions: "কার্যক্রম",
      frozen: "ফ্রিজড",
      active: "সক্রিয়",
      reset: "রিসেট",
      activate: "সক্রিয়",
      freeze: "ফ্রিজ",
      resetPasswordFor: "এর জন্য একটি নতুন পাসওয়ার্ড সেট করুন",
    },
    // Settings Page
    settings: {
      title: "সেটিংস",
      subtitle: "আপনার অ্যাকাউন্ট পছন্দসমূহ পরিচালনা করুন",
      profileTitle: "👤 প্রোফাইল তথ্য",
      roleLabel: "ভূমিকা",
      changePasswordTitle: "🔒 পাসওয়ার্ড পরিবর্তন",
      currentPasswordLabel: "বর্তমান পাসওয়ার্ড",
      newPasswordLabel: "নতুন পাসওয়ার্ড",
      confirmPasswordLabel: "নতুন পাসওয়ার্ড নিশ্চিত করুন",
      currentPasswordPlaceholder: "আপনার বর্তমান পাসওয়ার্ডটি লিখুন",
      newPasswordPlaceholder: "কমপক্ষে ৬ অক্ষরের হতে হবে",
      confirmPasswordPlaceholder: "••••••••",
      updatePasswordBtn: "পাসওয়ার্ড পরিবর্তন করুন",
      updatingBtn: "পরিবর্তন হচ্ছে...",
      passwordsDoNotMatch: "নতুন পাসওয়ার্ড দুটি মিলছে না",
      passwordTooShort: "নতুন পাসওয়ার্ডটি কমপক্ষে ৬ অক্ষরের হতে হবে",
      passwordChangedSuccess: "পাসওয়ার্ড সফলভাবে পরিবর্তন করা হয়েছে",
      profileInfo: "প্রোফাইল তথ্য",
      role: "ভূমিকা",
      roleAdmin: "অ্যাডমিন",
      roleUser: "ব্যবহারকারী",
      changePassword: "পাসওয়ার্ড পরিবর্তন",
      currentPassword: "বর্তমান পাসওয়ার্ড",
      currentPassPlaceholder: "আপনার বর্তমান পাসওয়ার্ডটি লিখুন",
      newPassPlaceholder: "কমপক্ষে ৬ অক্ষরের হতে হবে",
      confirmPassword: "নতুন পাসওয়ার্ড নিশ্চিত করুন",
    },
  },
};

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState('en');

  // Load language preference from local storage
  useEffect(() => {
    const savedLang = localStorage.getItem('financecalc_lang');
    if (savedLang === 'bn' || savedLang === 'en') {
      setLang(savedLang);
    }
  }, []);

  const toggleLang = () => {
    const newLang = lang === 'en' ? 'bn' : 'en';
    setLang(newLang);
    localStorage.setItem('financecalc_lang', newLang);
  };

  const t = (path) => {
    const keys = path.split('.');
    let result = translations[lang];
    for (const key of keys) {
      if (result && result[key] !== undefined) {
        result = result[key];
      } else {
        return path; // Fallback to path key itself
      }
    }
    return result;
  };

  const fmt = (n) => {
    if (lang === 'bn') {
      return `৳${(n || 0).toLocaleString('bn-BD')}`;
    }
    return `৳${(n || 0).toLocaleString('en-US')}`;
  };

  const fmtDate = (d) => {
    if (!d) return '—';
    const dateObj = new Date(d);
    if (lang === 'bn') {
      return dateObj.toLocaleDateString('bn-BD', { month: 'long', day: 'numeric', year: 'numeric' });
    }
    return dateObj.toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' });
  };

  return (
    <LanguageContext.Provider value={{ lang, toggleLang, t, fmt, fmtDate }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
